"""The folded stop word supplement of the Snowball chains, and nothing else.

Where it comes from: the Snowball stop word lists of tantivy, tag 0.26.2, file
``src/tokenizer/stop_word_filter/stopwords.rs`` for Dutch, Italian, Portuguese
and Spanish, and the inline Lucene list in ``mod.rs`` for English. What produced
it: ``scripts/dev/stopword_supplement.py``. It is not edited by hand. A hand
edit produces a supplement that no longer belongs to the list it supplements,
and the symptom of that is a stop word sitting in the index as a term.

Why it exists at all. The built in lists compare strings exactly and they carry
real accents. The chain in :mod:`findling.index.analyzer` folds before it
filters, because that is the only fold position measured to keep the accented
and the flat spelling of a word on one term. Once the fold has run, an entry
like the Spanish "esta" with an accent never matches again, and the flat form it
folded into is in no list at all. Measured on 2026-09-23 against tag 0.26.2: 77
Spanish, 10 Italian and 30 Portuguese stop words would leak into the index as
ordinary terms, in both spellings. This module is the 117 entries that close
that hole. Dutch has no accented entry, English has none either, so both are
empty here, and an empty custom stop word filter is measured to be a no-op.

Every entry is ASCII by construction: it is the folded form of an entry of the
built in list. Accents appear nowhere in this file, not even in a literal, which
is why this module needs no accent note of its own; the note that covers the
test data lives in ``backend/tests/test_language_analyzers.py``. Identifiers
stay ASCII as the project rules require.

**The supplement digest is not a version mark, and it may never become one.**
``folded_stopwords_hash`` below describes this list and belongs into a test. It
must not reach ``expected_versions()`` in :mod:`findling.index.open`. There it
would be a sixth mark, and a sixth mark exists on no installation in the field,
and ``Store.version_mismatch`` reads a missing mark as a difference. The result
would be a full reindex on every stock installation, measured at 19 h 20 min,
caused by a constant that changes no tokenisation of any index already written.
The one place this digest is allowed to stand is
``backend/tests/test_language_analyzers.py``, as ``FOLDED_SUPPLEMENT_SHA256``.

Digest of the list below, over the flattened entries in sorted language order:
d056d4597f989c7e03113c529c92cef980254f72c4d4e5deace4588ea033311a
"""

import hashlib
from collections.abc import Sequence
from typing import Final

# Encoding of the digest input. Spelled out here rather than imported from
# findling.index.wordlist: this module carries no other tie to the German
# constituent list, and one import for one string would be the whole coupling.
ENCODING = "utf-8"

# The supplement per Snowball language, generated by
# scripts/dev/stopword_supplement.py from tantivy tag 0.26.2. Keys are the
# language names tantivy itself accepts, so that a caller can hand the same
# string to Filter.stopword and to this mapping. Order of the entries inside a
# language is the order of first appearance in the built in list, because the
# generator preserves it and a resorted tuple would change the digest without
# changing the behaviour.
FOLDED_STOPWORDS: Final[dict[str, tuple[str, ...]]] = {
    "english": (),
    "spanish": (
        "mas",
        "si",
        "tambien",
        "mio",
        "mia",
        "mios",
        "mias",
        "estais",
        "estan",
        "estes",
        "esteis",
        "esten",
        "estare",
        "estaras",
        "estara",
        "estareis",
        "estaran",
        "estaria",
        "estarias",
        "estariamos",
        "estariais",
        "estarian",
        "estabamos",
        "estuvieramos",
        "estuviesemos",
        "habeis",
        "hayais",
        "habre",
        "habras",
        "habra",
        "habreis",
        "habran",
        "habria",
        "habrias",
        "habriamos",
        "habriais",
        "habrian",
        "habia",
        "habias",
        "habiamos",
        "habiais",
        "habian",
        "hubieramos",
        "hubiesemos",
        "seais",
        "sere",
        "seras",
        "sera",
        "sereis",
        "seran",
        "seria",
        "serias",
        "seriamos",
        "seriais",
        "serian",
        "eramos",
        "fueramos",
        "fuesemos",
        "teneis",
        "tengais",
        "tendre",
        "tendras",
        "tendra",
        "tendreis",
        "tendran",
        "tendria",
        "tendrias",
        "tendriamos",
        "tendriais",
        "tendrian",
        "tenia",
        "tenias",
        "teniamos",
        "teniais",
        "tenian",
        "tuvieramos",
        "tuviesemos",
    ),
    "italian": (
        "perche",
        "piu",
        "avro",
        "avra",
        "saro",
        "sara",
        "faro",
        "fara",
        "staro",
        "stara",
    ),
    "dutch": (),
    "portuguese": (
        "nao",
        "ja",
        "tambem",
        "so",
        "ate",
        "voce",
        "voces",
        "estao",
        "estavamos",
        "estiveramos",
        "estivessemos",
        "ha",
        "hao",
        "houveramos",
        "houvessemos",
        "houverao",
        "houveriamos",
        "sao",
        "eramos",
        "foramos",
        "fossemos",
        "sera",
        "serao",
        "seriamos",
        "tinhamos",
        "tiveramos",
        "tivessemos",
        "tera",
        "terao",
        "teriamos",
    ),
}


def folded_stopwords_hash(entries: Sequence[str]) -> str:
    """Return the SHA-256 of the supplement, stable across processes and machines.

    Hashing the joined entries rather than the source file is deliberate, for
    the same reason :func:`findling.index.wordlist.wordlist_hash` does it: what
    decides the behaviour is the derived list, not the bytes it came from. A
    tantivy point release that only reorders a Rust literal must not show up as
    a difference, and one accented entry more or less must.
    """
    digest = hashlib.sha256()
    digest.update("\n".join(entries).encode(ENCODING))
    return digest.hexdigest()
